version: '3.8'

services: 
  mcdonalds-server:
    image: postgres:15
    container_name: mcdonalds-server
    restart: always
    environment:
      POSTGRES_USER: mc-user
      POSTGRES_PASSWORD: y1sDI3D6DMmITJ6JPRtvfA
      POSTGRES_DB: mcdonalds-server
    ports:
      - "26257:26257"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data